# Generated by Django 4.0.3 on 2022-04-09 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('content_id', models.CharField(max_length=250)),
                ('media_type', models.CharField(max_length=250)),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(max_length=250)),
                ('backdrop_path', models.CharField(max_length=250)),
                ('vote_average', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
