# Generated by Django 4.0.4 on 2022-04-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_watched_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='review',
        ),
        migrations.RemoveField(
            model_name='watched',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='watched',
            name='review',
        ),
    ]
